#!/bin/sh
ls content-n3/java/org/mulgara/content/n3/N3ContentHandler.java > /dev/null
ls content-n3/java/org/mulgara/content/n3/N3Statements.java > /dev/null
ls content-n3/java/org/mulgara/content/n3/N3Writer.java > /dev/null
ls content-n3/java/org/mulgara/content/n3/Parser.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/Parser.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/RDFXMLContentHandler.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/RDFXMLStatements.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/writer/AbstractWritableStatement.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/writer/BlankNodeWritableStatement.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/writer/LiteralWritableStatement.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/writer/NamespaceMap.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/writer/RDFXMLWriter.java > /dev/null
ls content-rdfxml/java/org/mulgara/content/rdfxml/writer/URIReferenceWritableStatement.java > /dev/null
ls driver/java/org/mulgara/server/driver/JRDFGraphFactory.java > /dev/null
ls driver/java/org/mulgara/server/driver/SessionFactoryFinder.java > /dev/null
ls driver/java/org/mulgara/server/driver/SessionFactoryFinderException.java > /dev/null
ls dtd/java/org/mulgara/xml/DocumentBuilderFactoryWrapper.java > /dev/null
ls dtd/java/org/mulgara/xml/ResourceDocumentBuilderFactory.java > /dev/null
ls dtd/java/org/mulgara/xml/ResourceEntityResolver.java > /dev/null
ls jrdf/java/org/mulgara/jrdf/AnswerClosableIteratorImpl.java > /dev/null
ls jrdf/java/org/mulgara/jrdf/JRDFGraph.java > /dev/null
ls jrdf/java/org/mulgara/jrdf/JRDFGraphElementFactory.java > /dev/null
ls jrdf/java/org/mulgara/jrdf/JRDFTripleFactory.java > /dev/null
ls jrdf/java/org/mulgara/jrdf/LocalJRDFSession.java > /dev/null
ls query/java/org/jrdf/graph/AbstractBlankNode.java > /dev/null
ls query/java/org/jrdf/graph/AbstractLiteral.java > /dev/null
ls query/java/org/jrdf/graph/AbstractTriple.java > /dev/null
ls query/java/org/jrdf/graph/AbstractTripleFactory.java > /dev/null
ls query/java/org/jrdf/graph/AbstractURIReference.java > /dev/null
ls query/java/org/jrdf/graph/AlreadyReifiedException.java > /dev/null
ls query/java/org/jrdf/graph/Alternative.java > /dev/null
ls query/java/org/jrdf/graph/Bag.java > /dev/null
ls query/java/org/jrdf/graph/BlankNode.java > /dev/null
ls query/java/org/jrdf/graph/Collection.java > /dev/null
ls query/java/org/jrdf/graph/Container.java > /dev/null
ls query/java/org/jrdf/graph/Graph.java > /dev/null
ls query/java/org/jrdf/graph/GraphElementFactory.java > /dev/null
ls query/java/org/jrdf/graph/GraphElementFactoryException.java > /dev/null
ls query/java/org/jrdf/graph/GraphException.java > /dev/null
ls query/java/org/jrdf/graph/Literal.java > /dev/null
ls query/java/org/jrdf/graph/Node.java > /dev/null
ls query/java/org/jrdf/graph/ObjectNode.java > /dev/null
ls query/java/org/jrdf/graph/PredicateNode.java > /dev/null
ls query/java/org/jrdf/graph/Sequence.java > /dev/null
ls query/java/org/jrdf/graph/SubjectNode.java > /dev/null
ls query/java/org/jrdf/graph/Triple.java > /dev/null
ls query/java/org/jrdf/graph/TripleFactory.java > /dev/null
ls query/java/org/jrdf/graph/TripleFactoryException.java > /dev/null
ls query/java/org/jrdf/graph/TypedNodeVisitable.java > /dev/null
ls query/java/org/jrdf/graph/TypedNodeVisitor.java > /dev/null
ls query/java/org/jrdf/graph/TypedNodeVisitorAdapter.java > /dev/null
ls query/java/org/jrdf/graph/URIReference.java > /dev/null
ls query/java/org/jrdf/graph/mem/AbstractUnorderedContainer.java > /dev/null
ls query/java/org/jrdf/graph/mem/BlankNodeImpl.java > /dev/null
ls query/java/org/jrdf/graph/mem/EmptyClosableIterator.java > /dev/null
ls query/java/org/jrdf/graph/mem/GraphElementFactoryImpl.java > /dev/null
ls query/java/org/jrdf/graph/mem/GraphHandler.java > /dev/null
ls query/java/org/jrdf/graph/mem/GraphHandler012.java > /dev/null
ls query/java/org/jrdf/graph/mem/GraphHandler120.java > /dev/null
ls query/java/org/jrdf/graph/mem/GraphHandler201.java > /dev/null
ls query/java/org/jrdf/graph/mem/GraphImpl.java > /dev/null
ls query/java/org/jrdf/graph/mem/GraphIterator.java > /dev/null
ls query/java/org/jrdf/graph/mem/LiteralImpl.java > /dev/null
ls query/java/org/jrdf/graph/mem/MemNode.java > /dev/null
ls query/java/org/jrdf/graph/mem/OneFixedIterator.java > /dev/null
ls query/java/org/jrdf/graph/mem/SequenceImpl.java > /dev/null
ls query/java/org/jrdf/graph/mem/ThreeFixedIterator.java > /dev/null
ls query/java/org/jrdf/graph/mem/TripleFactoryImpl.java > /dev/null
ls query/java/org/jrdf/graph/mem/TripleImpl.java > /dev/null
ls query/java/org/jrdf/graph/mem/TwoFixedIterator.java > /dev/null
ls query/java/org/jrdf/graph/mem/URIReferenceImpl.java > /dev/null
ls query/java/org/jrdf/parser/ParserBlankNodeFactory.java > /dev/null
ls query/java/org/jrdf/parser/mem/ParserBlankNodeFactoryImpl.java > /dev/null
ls query/java/org/jrdf/util/ClosableIterator.java > /dev/null
ls query/java/org/jrdf/util/EscapeUtil.java > /dev/null
ls query/java/org/jrdf/util/param/EmtpyStringChecker.java > /dev/null
ls query/java/org/jrdf/util/param/NullChecker.java > /dev/null
ls query/java/org/jrdf/util/param/ParameterChecker.java > /dev/null
ls query/java/org/jrdf/util/param/ParameterUtil.java > /dev/null
ls query/java/org/jrdf/vocabulary/OWL.java > /dev/null
ls query/java/org/jrdf/vocabulary/RDF.java > /dev/null
ls query/java/org/jrdf/vocabulary/RDFS.java > /dev/null
ls query/java/org/jrdf/vocabulary/Vocabulary.java > /dev/null
ls query/java/org/mulgara/connection/CommandExecutor.java > /dev/null
ls query/java/org/mulgara/connection/Connection.java > /dev/null
ls query/java/org/mulgara/connection/ConnectionException.java > /dev/null
ls query/java/org/mulgara/connection/ConnectionFactory.java > /dev/null
ls query/java/org/mulgara/connection/DummyConnection.java > /dev/null
ls query/java/org/mulgara/connection/JenaConnection.java > /dev/null
ls query/java/org/mulgara/connection/JenaConnectionImpl.java > /dev/null
ls query/java/org/mulgara/connection/SessionConnection.java > /dev/null
ls query/java/org/mulgara/parser/Interpreter.java > /dev/null
ls query/java/org/mulgara/parser/MulgaraLexerException.java > /dev/null
ls query/java/org/mulgara/parser/MulgaraParserException.java > /dev/null
ls query/java/org/mulgara/query/AbstractAnswer.java > /dev/null
ls query/java/org/mulgara/query/AbstractConstraintExpression.java > /dev/null
ls query/java/org/mulgara/query/AggregateFunction.java > /dev/null
ls query/java/org/mulgara/query/Answer.java > /dev/null
ls query/java/org/mulgara/query/AnswerImpl.java > /dev/null
ls query/java/org/mulgara/query/AnswerOperations.java > /dev/null
ls query/java/org/mulgara/query/ArrayAnswer.java > /dev/null
ls query/java/org/mulgara/query/AskQuery.java > /dev/null
ls query/java/org/mulgara/query/BooleanAnswer.java > /dev/null
ls query/java/org/mulgara/query/ConstantValue.java > /dev/null
ls query/java/org/mulgara/query/Constraint.java > /dev/null
ls query/java/org/mulgara/query/ConstraintAssignment.java > /dev/null
ls query/java/org/mulgara/query/ConstraintBinaryOperation.java > /dev/null
ls query/java/org/mulgara/query/ConstraintConjunction.java > /dev/null
ls query/java/org/mulgara/query/ConstraintDifference.java > /dev/null
ls query/java/org/mulgara/query/ConstraintDisjunction.java > /dev/null
ls query/java/org/mulgara/query/ConstraintElement.java > /dev/null
ls query/java/org/mulgara/query/ConstraintExpression.java > /dev/null
ls query/java/org/mulgara/query/ConstraintFactory.java > /dev/null
ls query/java/org/mulgara/query/ConstraintFalse.java > /dev/null
ls query/java/org/mulgara/query/ConstraintFilter.java > /dev/null
ls query/java/org/mulgara/query/ConstraintHaving.java > /dev/null
ls query/java/org/mulgara/query/ConstraintImpl.java > /dev/null
ls query/java/org/mulgara/query/ConstraintIn.java > /dev/null
ls query/java/org/mulgara/query/ConstraintIs.java > /dev/null
ls query/java/org/mulgara/query/ConstraintNotOccurs.java > /dev/null
ls query/java/org/mulgara/query/ConstraintOccurs.java > /dev/null
ls query/java/org/mulgara/query/ConstraintOccursLessThan.java > /dev/null
ls query/java/org/mulgara/query/ConstraintOccursMoreThan.java > /dev/null
ls query/java/org/mulgara/query/ConstraintOperation.java > /dev/null
ls query/java/org/mulgara/query/ConstraintOptionalJoin.java > /dev/null
ls query/java/org/mulgara/query/ConstraintTrue.java > /dev/null
ls query/java/org/mulgara/query/ConstructQuery.java > /dev/null
ls query/java/org/mulgara/query/Count.java > /dev/null
ls query/java/org/mulgara/query/Cursor.java > /dev/null
ls query/java/org/mulgara/query/FunctionResolverRegistry.java > /dev/null
ls query/java/org/mulgara/query/GivenConstraint.java > /dev/null
ls query/java/org/mulgara/query/Graph.java > /dev/null
ls query/java/org/mulgara/query/GraphAnswer.java > /dev/null
ls query/java/org/mulgara/query/GraphExpression.java > /dev/null
ls query/java/org/mulgara/query/GraphIntersection.java > /dev/null
ls query/java/org/mulgara/query/GraphLiteral.java > /dev/null
ls query/java/org/mulgara/query/GraphOperation.java > /dev/null
ls query/java/org/mulgara/query/GraphResource.java > /dev/null
ls query/java/org/mulgara/query/GraphUnion.java > /dev/null
ls query/java/org/mulgara/query/GraphVariable.java > /dev/null
ls query/java/org/mulgara/query/LocalNode.java > /dev/null
ls query/java/org/mulgara/query/MulgaraTransactionException.java > /dev/null
ls query/java/org/mulgara/query/Order.java > /dev/null
ls query/java/org/mulgara/query/Query.java > /dev/null
ls query/java/org/mulgara/query/QueryException.java > /dev/null
ls query/java/org/mulgara/query/RdfXmlEmitter.java > /dev/null
ls query/java/org/mulgara/query/SelectElement.java > /dev/null
ls query/java/org/mulgara/query/SingleTransitiveConstraint.java > /dev/null
ls query/java/org/mulgara/query/SpecialPredicates.java > /dev/null
ls query/java/org/mulgara/query/Subquery.java > /dev/null
ls query/java/org/mulgara/query/Transformation.java > /dev/null
ls query/java/org/mulgara/query/TransformationException.java > /dev/null
ls query/java/org/mulgara/query/TransitiveConstraint.java > /dev/null
ls query/java/org/mulgara/query/TuplesException.java > /dev/null
ls query/java/org/mulgara/query/UnconstrainedAnswer.java > /dev/null
ls query/java/org/mulgara/query/Value.java > /dev/null
ls query/java/org/mulgara/query/Variable.java > /dev/null
ls query/java/org/mulgara/query/VariableFactory.java > /dev/null
ls query/java/org/mulgara/query/WalkConstraint.java > /dev/null
ls query/java/org/mulgara/query/filter/AbstractBooleanFn.java > /dev/null
ls query/java/org/mulgara/query/filter/AbstractContextOwner.java > /dev/null
ls query/java/org/mulgara/query/filter/AbstractFilterValue.java > /dev/null
ls query/java/org/mulgara/query/filter/And.java > /dev/null
ls query/java/org/mulgara/query/filter/BinaryComparisonFilter.java > /dev/null
ls query/java/org/mulgara/query/filter/BinaryTstFilter.java > /dev/null
ls query/java/org/mulgara/query/filter/BoundFn.java > /dev/null
ls query/java/org/mulgara/query/filter/Context.java > /dev/null
ls query/java/org/mulgara/query/filter/ContextOwner.java > /dev/null
ls query/java/org/mulgara/query/filter/Equals.java > /dev/null
ls query/java/org/mulgara/query/filter/Filter.java > /dev/null
ls query/java/org/mulgara/query/filter/GreaterThan.java > /dev/null
ls query/java/org/mulgara/query/filter/GreaterThanEqualTo.java > /dev/null
ls query/java/org/mulgara/query/filter/Inverse.java > /dev/null
ls query/java/org/mulgara/query/filter/IsBlankFn.java > /dev/null
ls query/java/org/mulgara/query/filter/IsIriFn.java > /dev/null
ls query/java/org/mulgara/query/filter/IsLiteralFn.java > /dev/null
ls query/java/org/mulgara/query/filter/IsUriFn.java > /dev/null
ls query/java/org/mulgara/query/filter/LangMatches.java > /dev/null
ls query/java/org/mulgara/query/filter/LessThan.java > /dev/null
ls query/java/org/mulgara/query/filter/LessThanEqualTo.java > /dev/null
ls query/java/org/mulgara/query/filter/NAryOperatorFilter.java > /dev/null
ls query/java/org/mulgara/query/filter/Not.java > /dev/null
ls query/java/org/mulgara/query/filter/NotEquals.java > /dev/null
ls query/java/org/mulgara/query/filter/Or.java > /dev/null
ls query/java/org/mulgara/query/filter/RDFTerm.java > /dev/null
ls query/java/org/mulgara/query/filter/RegexFn.java > /dev/null
ls query/java/org/mulgara/query/filter/SameTerm.java > /dev/null
ls query/java/org/mulgara/query/filter/arithmetic/AbstractNumericOperation.java > /dev/null
ls query/java/org/mulgara/query/filter/arithmetic/AddOperation.java > /dev/null
ls query/java/org/mulgara/query/filter/arithmetic/BinaryOperation.java > /dev/null
ls query/java/org/mulgara/query/filter/arithmetic/DivideOperation.java > /dev/null
ls query/java/org/mulgara/query/filter/arithmetic/MinusOperation.java > /dev/null
ls query/java/org/mulgara/query/filter/arithmetic/MultiplyOperation.java > /dev/null
ls query/java/org/mulgara/query/filter/arithmetic/UnaryMinus.java > /dev/null
ls query/java/org/mulgara/query/filter/value/AbstractAccessorFn.java > /dev/null
ls query/java/org/mulgara/query/filter/value/AbstractComparable.java > /dev/null
ls query/java/org/mulgara/query/filter/value/AbstractComparableLiteral.java > /dev/null
ls query/java/org/mulgara/query/filter/value/BlankNodeValue.java > /dev/null
ls query/java/org/mulgara/query/filter/value/Bool.java > /dev/null
ls query/java/org/mulgara/query/filter/value/ComparableExpression.java > /dev/null
ls query/java/org/mulgara/query/filter/value/DataTypeFn.java > /dev/null
ls query/java/org/mulgara/query/filter/value/DateTime.java > /dev/null
ls query/java/org/mulgara/query/filter/value/ExternalFn.java > /dev/null
ls query/java/org/mulgara/query/filter/value/IRI.java > /dev/null
ls query/java/org/mulgara/query/filter/value/LangFn.java > /dev/null
ls query/java/org/mulgara/query/filter/value/NumericExpression.java > /dev/null
ls query/java/org/mulgara/query/filter/value/NumericLiteral.java > /dev/null
ls query/java/org/mulgara/query/filter/value/SimpleLiteral.java > /dev/null
ls query/java/org/mulgara/query/filter/value/StrFn.java > /dev/null
ls query/java/org/mulgara/query/filter/value/TypedLiteral.java > /dev/null
ls query/java/org/mulgara/query/filter/value/ValueLiteral.java > /dev/null
ls query/java/org/mulgara/query/filter/value/Var.java > /dev/null
ls query/java/org/mulgara/query/functions/MulgaraFunction.java > /dev/null
ls query/java/org/mulgara/query/functions/MulgaraFunctionGroup.java > /dev/null
ls query/java/org/mulgara/query/functions/MulgaraFunctionResolver.java > /dev/null
ls query/java/org/mulgara/query/functions/MulgaraUnsafeFunctionResolver.java > /dev/null
ls query/java/org/mulgara/query/functions/MulgaraXFunctionGroup.java > /dev/null
ls query/java/org/mulgara/query/operation/AbstractCommand.java > /dev/null
ls query/java/org/mulgara/query/operation/AddAlias.java > /dev/null
ls query/java/org/mulgara/query/operation/ApplyRules.java > /dev/null
ls query/java/org/mulgara/query/operation/Backup.java > /dev/null
ls query/java/org/mulgara/query/operation/BooleanSetCommand.java > /dev/null
ls query/java/org/mulgara/query/operation/Command.java > /dev/null
ls query/java/org/mulgara/query/operation/Commit.java > /dev/null
ls query/java/org/mulgara/query/operation/CreateGraph.java > /dev/null
ls query/java/org/mulgara/query/operation/DataInputTx.java > /dev/null
ls query/java/org/mulgara/query/operation/DataOutputTx.java > /dev/null
ls query/java/org/mulgara/query/operation/DataTx.java > /dev/null
ls query/java/org/mulgara/query/operation/Deletion.java > /dev/null
ls query/java/org/mulgara/query/operation/DropGraph.java > /dev/null
ls query/java/org/mulgara/query/operation/ExecuteScript.java > /dev/null
ls query/java/org/mulgara/query/operation/Export.java > /dev/null
ls query/java/org/mulgara/query/operation/Help.java > /dev/null
ls query/java/org/mulgara/query/operation/Insertion.java > /dev/null
ls query/java/org/mulgara/query/operation/ListAlias.java > /dev/null
ls query/java/org/mulgara/query/operation/Load.java > /dev/null
ls query/java/org/mulgara/query/operation/LocalCommand.java > /dev/null
ls query/java/org/mulgara/query/operation/Modification.java > /dev/null
ls query/java/org/mulgara/query/operation/NullOp.java > /dev/null
ls query/java/org/mulgara/query/operation/Quit.java > /dev/null
ls query/java/org/mulgara/query/operation/Restore.java > /dev/null
ls query/java/org/mulgara/query/operation/Rollback.java > /dev/null
ls query/java/org/mulgara/query/operation/ServerCommand.java > /dev/null
ls query/java/org/mulgara/query/operation/SessionCommand.java > /dev/null
ls query/java/org/mulgara/query/operation/SetAutoCommit.java > /dev/null
ls query/java/org/mulgara/query/operation/SetCommand.java > /dev/null
ls query/java/org/mulgara/query/operation/SetTime.java > /dev/null
ls query/java/org/mulgara/query/operation/SetUser.java > /dev/null
ls query/java/org/mulgara/query/operation/TransactionCommand.java > /dev/null
ls query/java/org/mulgara/query/operation/TxOp.java > /dev/null
ls query/java/org/mulgara/query/rdf/BlankNodeImpl.java > /dev/null
ls query/java/org/mulgara/query/rdf/Krule.java > /dev/null
ls query/java/org/mulgara/query/rdf/LiteralImpl.java > /dev/null
ls query/java/org/mulgara/query/rdf/MimeTypes.java > /dev/null
ls query/java/org/mulgara/query/rdf/Mulgara.java > /dev/null
ls query/java/org/mulgara/query/rdf/SWRL.java > /dev/null
ls query/java/org/mulgara/query/rdf/TripleImpl.java > /dev/null
ls query/java/org/mulgara/query/rdf/URIReferenceImpl.java > /dev/null
ls query/java/org/mulgara/query/rdf/VariableNodeImpl.java > /dev/null
ls query/java/org/mulgara/query/rdf/XSD.java > /dev/null
ls query/java/org/mulgara/query/rdf/XSDAbbrev.java > /dev/null
ls query/java/org/mulgara/query/xpath/AfnFunctionGroup.java > /dev/null
ls query/java/org/mulgara/query/xpath/FnFunctionGroup.java > /dev/null
ls query/java/org/mulgara/query/xpath/MulgaraXPathFunctionResolver.java > /dev/null
ls query/java/org/mulgara/query/xpath/OpFunctionGroup.java > /dev/null
ls query/java/org/mulgara/query/xpath/SmfFunctionGroup.java > /dev/null
ls query/java/org/mulgara/query/xpath/SparqlFunctionGroup.java > /dev/null
ls query/java/org/mulgara/rules/DummyRuleLoader.java > /dev/null
ls query/java/org/mulgara/rules/InitializerException.java > /dev/null
ls query/java/org/mulgara/rules/RuleLoader.java > /dev/null
ls query/java/org/mulgara/rules/RuleLoaderFactory.java > /dev/null
ls query/java/org/mulgara/rules/Rules.java > /dev/null
ls query/java/org/mulgara/rules/RulesException.java > /dev/null
ls query/java/org/mulgara/rules/RulesRef.java > /dev/null
ls query/java/org/mulgara/rules/RulesRefImpl.java > /dev/null
ls query/java/org/mulgara/server/JRDFFactory.java > /dev/null
ls query/java/org/mulgara/server/JRDFSession.java > /dev/null
ls query/java/org/mulgara/server/JenaFactory.java > /dev/null
ls query/java/org/mulgara/server/JenaSession.java > /dev/null
ls query/java/org/mulgara/server/NonRemoteSessionException.java > /dev/null
ls query/java/org/mulgara/server/ResourceManagerInstanceAdaptor.java > /dev/null
ls query/java/org/mulgara/server/Session.java > /dev/null
ls query/java/org/mulgara/server/SessionFactory.java > /dev/null
ls query/java/org/mulgara/server/SessionFactoryConfiguration.java > /dev/null
ls query/java/org/mulgara/server/SessionFactoryException.java > /dev/null
ls query/java/org/mulgara/server/SessionFactoryFactory.java > /dev/null
ls query/java/org/mulgara/server/SessionFactoryProvider.java > /dev/null
ls driver/java/org/mulgara/server/driver/JRDFGraphFactory.java > /dev/null
ls driver/java/org/mulgara/server/driver/SessionFactoryFinder.java > /dev/null
ls driver/java/org/mulgara/server/driver/SessionFactoryFinderException.java > /dev/null
ls resolver/java/org/mulgara/resolver/AnswerOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/AnswerOperationResult.java > /dev/null
ls resolver/java/org/mulgara/resolver/AppendAggregateTuples.java > /dev/null
ls resolver/java/org/mulgara/resolver/ApplyRulesOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/BackupConstants.java > /dev/null
ls resolver/java/org/mulgara/resolver/BackupOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/BootstrapOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/BuildRulesOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/CacheResolver.java > /dev/null
ls resolver/java/org/mulgara/resolver/CacheResolverFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/CacheStatements.java > /dev/null
ls resolver/java/org/mulgara/resolver/ConfigurationException.java > /dev/null
ls resolver/java/org/mulgara/resolver/ConstraintOperations.java > /dev/null
ls resolver/java/org/mulgara/resolver/ContentFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/ContentHandlerFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/ContentHandlerManagerImpl.java > /dev/null
ls resolver/java/org/mulgara/resolver/CreateDefaultGraphOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/CreateGraphOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/Database.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseFactoryInitializer.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseInitializer.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseMetadataImpl.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseOperationContext.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseResolverFactoryInitializer.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseSecurityAdapterInitializer.java > /dev/null
ls resolver/java/org/mulgara/resolver/DatabaseSession.java > /dev/null
ls resolver/java/org/mulgara/resolver/DefaultConstraintHandlers.java > /dev/null
ls resolver/java/org/mulgara/resolver/DirectTransitiveFunction.java > /dev/null
ls resolver/java/org/mulgara/resolver/ExhaustiveTransitiveFunction.java > /dev/null
ls resolver/java/org/mulgara/resolver/ExportOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/GlobalizedAnswer.java > /dev/null
ls resolver/java/org/mulgara/resolver/GraphExistsOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/InternalResolver.java > /dev/null
ls resolver/java/org/mulgara/resolver/InternalResolverFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/InternalSystemResolverFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/JRDFFactoryImpl.java > /dev/null
ls resolver/java/org/mulgara/resolver/JRDFResolverSession.java > /dev/null
ls resolver/java/org/mulgara/resolver/JRDFResolverSessionFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/JenaFactoryImpl.java > /dev/null
ls resolver/java/org/mulgara/resolver/JotmTransactionManagerFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/JotmTransactionStandaloneIntTst.java > /dev/null
ls resolver/java/org/mulgara/resolver/LocalJRDFDatabaseSession.java > /dev/null
ls resolver/java/org/mulgara/resolver/LocalQueryResolver.java > /dev/null
ls resolver/java/org/mulgara/resolver/LoginOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/MockResolver.java > /dev/null
ls resolver/java/org/mulgara/resolver/MockResolverFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/ModifyGraphOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraExternalTransaction.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraExternalTransactionFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraInternalTransaction.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraInternalTransactionFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraTransaction.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraTransactionFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraTransactionManager.java > /dev/null
ls resolver/java/org/mulgara/resolver/MulgaraXAResourceContext.java > /dev/null
ls resolver/java/org/mulgara/resolver/MutableLocalQueryImpl.java > /dev/null
ls resolver/java/org/mulgara/resolver/NTriples.java > /dev/null
ls resolver/java/org/mulgara/resolver/Operation.java > /dev/null
ls resolver/java/org/mulgara/resolver/OperationContext.java > /dev/null
ls resolver/java/org/mulgara/resolver/OrderByRowComparator.java > /dev/null
ls resolver/java/org/mulgara/resolver/OutputOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/PersistentResolverSession.java > /dev/null
ls resolver/java/org/mulgara/resolver/PreallocateOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/PrimitiveConstraintDescriptor.java > /dev/null
ls resolver/java/org/mulgara/resolver/QueryOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/RemoveGraphOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/ResolverFactoryFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/RestoreOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/SetGraphOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/StatusFormat.java > /dev/null
ls resolver/java/org/mulgara/resolver/StreamContent.java > /dev/null
ls resolver/java/org/mulgara/resolver/StringPoolSession.java > /dev/null
ls resolver/java/org/mulgara/resolver/StringPoolSessionFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/SubqueryAnswer.java > /dev/null
ls resolver/java/org/mulgara/resolver/SystemGraphSecurityAdapter.java > /dev/null
ls resolver/java/org/mulgara/resolver/TransactionOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/TransactionalAnswer.java > /dev/null
ls resolver/java/org/mulgara/resolver/TransitiveFunction.java > /dev/null
ls resolver/java/org/mulgara/resolver/TuplesBasedOperation.java > /dev/null
ls resolver/java/org/mulgara/resolver/WalkFunction.java > /dev/null
ls resolver/java/org/mulgara/resolver/jrdf/BlankNodeMap.java > /dev/null
ls resolver/java/org/mulgara/resolver/jrdf/BlankNodeMapFactory.java > /dev/null
ls resolver/java/org/mulgara/resolver/jrdf/DiskBlankNodeMap.java > /dev/null
ls resolver/java/org/mulgara/resolver/jrdf/MemoryBlankNodeMap.java > /dev/null
ls resolver/java/org/mulgara/store/exporter/GraphN3Writer.java > /dev/null
ls resolver/java/org/mulgara/store/exporter/GraphWriter.java > /dev/null
ls resolver/java/org/mulgara/store/exporter/GraphXMLWriter.java > /dev/null
ls resolver-memory/java/org/mulgara/resolver/memory/MemoryResolution.java > /dev/null
ls resolver-memory/java/org/mulgara/resolver/memory/MemoryResolver.java > /dev/null
ls resolver-memory/java/org/mulgara/resolver/memory/MemoryResolverFactory.java > /dev/null
ls resolver-memory/java/org/mulgara/resolver/memory/MemoryXAResource.java > /dev/null
ls resolver-memory/java/org/mulgara/resolver/memory/Stating.java > /dev/null
ls resolver-nodetype/java/org/mulgara/resolver/nodetype/NodeTypeResolver.java > /dev/null
ls resolver-nodetype/java/org/mulgara/resolver/nodetype/NodeTypeResolverFactory.java > /dev/null
ls resolver-nodetype/java/org/mulgara/resolver/nodetype/TuplesWrapperResolution.java > /dev/null
ls resolver-null/java/org/mulgara/resolver/nullres/NullResolution.java > /dev/null
ls resolver-null/java/org/mulgara/resolver/nullres/NullResolver.java > /dev/null
ls resolver-null/java/org/mulgara/resolver/nullres/NullResolverFactory.java > /dev/null
ls resolver-prefix/java/org/mulgara/resolver/prefix/PrefixResolver.java > /dev/null
ls resolver-prefix/java/org/mulgara/resolver/prefix/PrefixResolverFactory.java > /dev/null
ls resolver-prefix/java/org/mulgara/resolver/prefix/TuplesWrapperResolution.java > /dev/null
ls resolver-store/java/org/mulgara/resolver/store/StatementStoreResolution.java > /dev/null
ls resolver-store/java/org/mulgara/resolver/store/StatementStoreResolver.java > /dev/null
ls resolver-store/java/org/mulgara/resolver/store/StatementStoreResolverFactory.java > /dev/null
ls resolver-store/java/org/mulgara/resolver/store/StatementStoreXAResource.java > /dev/null
ls resolver-store/java/org/mulgara/resolver/store/XA11StatementStoreResolverFactory.java > /dev/null
ls resolver-store/java/org/mulgara/store/statement/xa/TripleAVLFile.java > /dev/null
ls resolver-store/java/org/mulgara/store/statement/xa/TripleWriteThread.java > /dev/null
ls resolver-store/java/org/mulgara/store/statement/xa/XAStatementStoreImpl.java > /dev/null
ls resolver-store/java/org/mulgara/store/statement/xa11/LiteralGraphTuples.java > /dev/null
ls resolver-store/java/org/mulgara/store/statement/xa11/XA11StatementStoreImpl.java > /dev/null
ls resolver-view/java/org/mulgara/resolver/view/ViewDefinition.java > /dev/null
ls resolver-view/java/org/mulgara/resolver/view/ViewDefinitionIntersection.java > /dev/null
ls resolver-view/java/org/mulgara/resolver/view/ViewDefinitionUnion.java > /dev/null
ls resolver-view/java/org/mulgara/resolver/view/ViewResolution.java > /dev/null
ls resolver-view/java/org/mulgara/resolver/view/ViewResolver.java > /dev/null
ls resolver-view/java/org/mulgara/resolver/view/ViewResolverFactory.java > /dev/null
ls resolver-xsd/java/org/mulgara/resolver/xsd/Bound.java > /dev/null
ls resolver-xsd/java/org/mulgara/resolver/xsd/IntervalConstraint.java > /dev/null
ls resolver-xsd/java/org/mulgara/resolver/xsd/IntervalConstraintDescriptor.java > /dev/null
ls resolver-xsd/java/org/mulgara/resolver/xsd/IntervalTransformation.java > /dev/null
ls resolver-xsd/java/org/mulgara/resolver/xsd/XSDResolution.java > /dev/null
ls resolver-xsd/java/org/mulgara/resolver/xsd/XSDResolver.java > /dev/null
ls resolver-xsd/java/org/mulgara/resolver/xsd/XSDResolverFactory.java > /dev/null
ls server/java/org/mulgara/server/AbstractServer.java > /dev/null
ls server/java/org/mulgara/server/EmbeddedMulgaraOptionParser.java > /dev/null
ls server/java/org/mulgara/server/EmbeddedMulgaraServer.java > /dev/null
ls server/java/org/mulgara/server/ExceptionList.java > /dev/null
ls server/java/org/mulgara/server/HttpServices.java > /dev/null
ls server/java/org/mulgara/server/MulgaraUserConfig.java > /dev/null
ls server/java/org/mulgara/server/ServerInfo.java > /dev/null
ls server/java/org/mulgara/server/ServerMBean.java > /dev/null
ls server/java/org/mulgara/server/ServiceListingServlet.java > /dev/null
ls server/java/org/mulgara/server/ServletMulgaraServer.java > /dev/null
ls server-local/java/org/mulgara/server/local/LocalSessionFactory.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/AnswerPage.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/AnswerPageImpl.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/AnswerWrapperRemoteAnswer.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/AnswerWrapperRemoteAnswerSerialised.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/AnswerWrapperRemoteAnswer_Skel.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/AnswerWrapperRemoteAnswer_Stub.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/BlankNodeWrapperAnswer.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/Handler.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/IteratorPage.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/IteratorPageImpl.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/JRDFSessionWrapperRemoteJRDFSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/JenaSessionWrapperRemoteJenaSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/PagedRemoteAnswer.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RMITimeoutException.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteAnswer.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteAnswerWrapperAnswer.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteJRDFSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteJRDFSessionImpl.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteJenaSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteJenaSessionImpl.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteSessionFactory.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteSessionFactoryImpl.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteSessionImpl.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteSessionWrapperJRDFSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteSessionWrapperJenaSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteSessionWrapperSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteXAResource.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RemoteXAResourceWrapperXAResource.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RmiServer.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RmiServerMBean.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RmiSessionFactory.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/RmiURLConnection.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/SessionWrapperRemoteSession.java > /dev/null
ls server-rmi/java/org/mulgara/server/rmi/XAResourceWrapperRemoteXAResource.java > /dev/null
ls store-nodepool-memory/java/org/mulgara/store/nodepool/memory/MemoryNodePoolFactory.java > /dev/null
ls store-nodepool-memory/java/org/mulgara/store/nodepool/memory/MemoryNodePoolImpl.java > /dev/null
ls store-nodepool-xa/java/org/mulgara/store/nodepool/xa/XANodePoolFactory.java > /dev/null
ls store-nodepool-xa/java/org/mulgara/store/nodepool/xa/XANodePoolImpl.java > /dev/null
ls store-stringpool-memory/java/org/mulgara/store/stringpool/memory/MemoryStringPoolFactory.java > /dev/null
ls store-stringpool-memory/java/org/mulgara/store/stringpool/memory/MemoryStringPoolImpl.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/BlankNodeAllocator.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/BlankNodeMapper.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/DataAVLComparator.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/DataCategoryAVLComparator.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/DataCategoryTypeAVLComparator.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/DataStruct.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/XA11StringPoolFactory.java > /dev/null
ls store-stringpool-xa11/java/org/mulgara/store/stringpool/xa11/XA11StringPoolImpl.java > /dev/null
ls resolver-spi/java/org/mulgara/content/Content.java > /dev/null
ls resolver-spi/java/org/mulgara/content/ContentHandler.java > /dev/null
ls resolver-spi/java/org/mulgara/content/ContentHandlerException.java > /dev/null
ls resolver-spi/java/org/mulgara/content/ContentHandlerManager.java > /dev/null
ls resolver-spi/java/org/mulgara/content/ContentResolver.java > /dev/null
ls resolver-spi/java/org/mulgara/content/CorruptContentException.java > /dev/null
ls resolver-spi/java/org/mulgara/content/ModifiedException.java > /dev/null
ls resolver-spi/java/org/mulgara/content/NotModifiedException.java > /dev/null
ls resolver-spi/java/org/mulgara/content/NotModifiedTuplesException.java > /dev/null
ls resolver-spi/java/org/mulgara/content/ValidatingContentHandler.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/AbstractSymbolicTransformer.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/AbstractXAResource.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/BackupRestoreSession.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConjunctiveTransformer.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConstraintBindingHandler.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConstraintDescriptor.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConstraintExpansion.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConstraintGraphRewrite.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConstraintLocalization.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConstraintResolutionHandler.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ConstraintVariableRewrite.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/DatabaseMetadata.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/DummyXAResource.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/DuplicateVariableTransformer.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/EmptyResolution.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/EnlistableResource.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/FactoryInitializer.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/GlobalizeException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/GraphExpansion.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/GraphResolutionHandler.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/InitializerException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/LocalSession.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/LocalizeException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/LocalizedTuples.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/MutableLocalQuery.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/NoSystemResolverFactoryException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/NullSecurityAdapter.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/PersistTuplesWrapperStatements.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/QueryEvaluationContext.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ReresolvableResolution.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/Resolution.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/Resolver.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ResolverException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ResolverFactory.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ResolverFactoryException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ResolverFactoryInitializer.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ResolverSession.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ResolverSessionFactory.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/ResolverSessionFactoryException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SecurityAdapter.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SecurityAdapterFactory.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SecurityAdapterFactoryException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SecurityAdapterInitializer.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SingletonStatements.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/Statements.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/StatementsWrapperResolution.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/StatementsWrapperTuples.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SumOfProductExpansionTransformer.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SymbolicTransformation.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SymbolicTransformationContext.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SymbolicTransformationException.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SystemResolver.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/SystemResolverFactory.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/TripleSetWrapperStatements.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/TuplesContext.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/TuplesWrapperResolution.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/spi/TuplesWrapperStatements.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/view/SessionView.java > /dev/null
ls resolver-spi/java/org/mulgara/resolver/view/ViewMarker.java > /dev/null
ls store/java/org/mulgara/store/StoreException.java > /dev/null
ls store-nodepool/java/org/mulgara/store/nodepool/NewNodeListener.java > /dev/null
ls store-nodepool/java/org/mulgara/store/nodepool/NoSuchNodeException.java > /dev/null
ls store-nodepool/java/org/mulgara/store/nodepool/NodePool.java > /dev/null
ls store-nodepool/java/org/mulgara/store/nodepool/NodePoolException.java > /dev/null
ls store-nodepool/java/org/mulgara/store/nodepool/NodePoolFactory.java > /dev/null
ls store-nodepool/java/org/mulgara/store/nodepool/ReleaseNodeListener.java > /dev/null
ls resolver-spi/java/org/mulgara/store/statement/StatementStore.java > /dev/null
ls resolver-spi/java/org/mulgara/store/statement/StatementStoreException.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/AbstractSPObject.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/AbstractSPStringComparator.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/AbstractSPTypedLiteral.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPComparator.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPDouble.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPLimit.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPObject.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPObjectFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPString.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPTypedLiteral.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPTypedLiteralFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/SPURI.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/StringPool.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/StringPoolException.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/StringPoolFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/AbstractSPGDateTime.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPBase64BinaryFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPBase64BinaryImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPBinaryComparator.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPBooleanFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPBooleanImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPCaseInsensitiveStringComparator.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPCaseSensitiveStringComparator.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDateFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDateImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDateTimeFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDateTimeImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDecimalBaseImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDecimalExtImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDecimalFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDecimalImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDoubleFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPDoubleImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPFloatFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPFloatImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGDayFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGDayImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGMonthDayFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGMonthDayImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGMonthFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGMonthImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGYearFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGYearImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGYearMonthFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPGYearMonthImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPHexBinaryFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPHexBinaryImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPNumber.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPObjectFactoryImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPStringImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPTypedLiteralRegistry.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPURIImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPXMLLiteralFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPXMLLiteralImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPXSDStringFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/SPXSDStringImpl.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/UnknownSPTypedLiteralFactory.java > /dev/null
ls store-stringpool/java/org/mulgara/store/stringpool/xa/UnknownSPTypedLiteralImpl.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/AbstractTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/Annotation.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/Assignment.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/DefaultRowComparator.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/DefinablePrefixAnnotation.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/DenseLongMatrix.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/Difference.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/DistinctTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/EmptyTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/ExpandedProjection.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/FilteredTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/HavingPredicates.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/JoinTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/LeftFiltered.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/LeftJoin.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/LetTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/LimitedTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/LiteralTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/MandatoryBindingAnnotation.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/MemoryTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/MemoryTuplesFactory.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/OffsetTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/OrderedAppend.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/OrderedProjection.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/OrderedStoreAppend.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/PartialColumnComparator.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/ReorderAnnotation.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/RestrictPredicate.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/RestrictPredicateFactory.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/RestrictPredicatePrototype.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/RestrictionTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/RowComparator.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/SimpleTuplesFormat.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/StoreTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/Tuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/TuplesFactory.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/TuplesOperations.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/UnboundJoin.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/UnconstrainedTuples.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/UnorderedAppend.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/UnorderedProjection.java > /dev/null
ls tuples/java/org/mulgara/store/tuples/WrappedTuples.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/SimpleXARecoveryHandler.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/SimpleXAResource.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/SimpleXAResourceException.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/XANodePool.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/XAResolverSession.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/XAResolverSessionFactory.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/XAStatementStore.java > /dev/null
ls store-xa/java/org/mulgara/store/xa/XAStringPool.java > /dev/null
ls resolver-spi/java/org/mulgara/transaction/TransactionManagerFactory.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/bdb/DbEnvironment.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/bdb/DbTuples.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/bdb/DbTuplesFactory.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/xa/BlockCacheLine.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/xa/CacheLine.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/xa/HybridTuples.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/xa/HybridTuplesFactory.java > /dev/null
ls tuples-hybrid/java/org/mulgara/store/xa/MemoryCacheLine.java > /dev/null
ls util/java/org/mulgara/util/AbstractMulgaraResultSet.java > /dev/null
ls util/java/org/mulgara/util/Assoc1toNMap.java > /dev/null
ls util/java/org/mulgara/util/BooleanOp.java > /dev/null
ls util/java/org/mulgara/util/BooleanOp2.java > /dev/null
ls util/java/org/mulgara/util/Bootstrap.java > /dev/null
ls util/java/org/mulgara/util/ClassDescriber.java > /dev/null
ls util/java/org/mulgara/util/ClassDescriberXML.java > /dev/null
ls util/java/org/mulgara/util/ClasspathDesc.java > /dev/null
ls util/java/org/mulgara/util/Closable.java > /dev/null
ls util/java/org/mulgara/util/Constants.java > /dev/null
ls util/java/org/mulgara/util/ExplicitIntFile.java > /dev/null
ls util/java/org/mulgara/util/FileUtil.java > /dev/null
ls util/java/org/mulgara/util/IntFile.java > /dev/null
ls util/java/org/mulgara/util/JettyLogger.java > /dev/null
ls util/java/org/mulgara/util/LexicalDateTime.java > /dev/null
ls util/java/org/mulgara/util/LongMapper.java > /dev/null
ls util/java/org/mulgara/util/LongToStringMap.java > /dev/null
ls util/java/org/mulgara/util/MapWrapper.java > /dev/null
ls util/java/org/mulgara/util/MappedIntFile.java > /dev/null
ls util/java/org/mulgara/util/MemLongMapper.java > /dev/null
ls util/java/org/mulgara/util/MemoryResultSet.java > /dev/null
ls util/java/org/mulgara/util/MulgaraResultSet.java > /dev/null
ls util/java/org/mulgara/util/Multimap.java > /dev/null
ls util/java/org/mulgara/util/NVPair.java > /dev/null
ls util/java/org/mulgara/util/NumberUtil.java > /dev/null
ls util/java/org/mulgara/util/ObjectUtil.java > /dev/null
ls util/java/org/mulgara/util/QueryParams.java > /dev/null
ls util/java/org/mulgara/util/Reflect.java > /dev/null
ls util/java/org/mulgara/util/ResultSetMetaDataImpl.java > /dev/null
ls util/java/org/mulgara/util/ResultSetRow.java > /dev/null
ls util/java/org/mulgara/util/Rmi.java > /dev/null
ls util/java/org/mulgara/util/RowList.java > /dev/null
ls util/java/org/mulgara/util/ServerInfoRef.java > /dev/null
ls util/java/org/mulgara/util/ServerURIHandler.java > /dev/null
ls util/java/org/mulgara/util/SoapClient.java > /dev/null
ls util/java/org/mulgara/util/SparqlUtil.java > /dev/null
ls util/java/org/mulgara/util/StackTrace.java > /dev/null
ls util/java/org/mulgara/util/StringToLongMap.java > /dev/null
ls util/java/org/mulgara/util/StringUtil.java > /dev/null
ls util/java/org/mulgara/util/TeePrintWriter.java > /dev/null
ls util/java/org/mulgara/util/TempDir.java > /dev/null
ls util/java/org/mulgara/util/ThreadUtil.java > /dev/null
ls util/java/org/mulgara/util/Timezone.java > /dev/null
ls util/java/org/mulgara/util/UIDGenerator.java > /dev/null
ls util/java/org/mulgara/util/URIUtil.java > /dev/null
ls util/java/org/mulgara/util/WebBrowser.java > /dev/null
ls util/java/org/mulgara/util/functional/C.java > /dev/null
ls util/java/org/mulgara/util/functional/F.java > /dev/null
ls util/java/org/mulgara/util/functional/Fn.java > /dev/null
ls util/java/org/mulgara/util/functional/Fn1.java > /dev/null
ls util/java/org/mulgara/util/functional/Fn1E.java > /dev/null
ls util/java/org/mulgara/util/functional/Fn2.java > /dev/null
ls util/java/org/mulgara/util/functional/Fn2E.java > /dev/null
ls util/java/org/mulgara/util/functional/FnE.java > /dev/null
ls util/java/org/mulgara/util/functional/Pair.java > /dev/null
ls util/java/org/mulgara/util/io/ArrayBufferSetWrapper.java > /dev/null
ls util/java/org/mulgara/util/io/Bytes.java > /dev/null
ls util/java/org/mulgara/util/io/FileHashMap.java > /dev/null
ls util/java/org/mulgara/util/io/FixedLengthSerializable.java > /dev/null
ls util/java/org/mulgara/util/io/IOUtil.java > /dev/null
ls util/java/org/mulgara/util/io/LBufferedFile.java > /dev/null
ls util/java/org/mulgara/util/io/LIOBufferedFile.java > /dev/null
ls util/java/org/mulgara/util/io/LLHashMap.java > /dev/null
ls util/java/org/mulgara/util/io/LMappedBufferedFile.java > /dev/null
ls util/java/org/mulgara/util/io/LMappedBufferedFileRO.java > /dev/null
ls util/java/org/mulgara/util/io/LMappedBufferedFileRW.java > /dev/null
ls util/java/org/mulgara/util/io/LReadOnlyIOBufferedFile.java > /dev/null
ls util/java/org/mulgara/util/io/MappingUtil.java > /dev/null
ls util/java/org/mulgara/util/io/RecordFile.java > /dev/null
ls util/java/org/mulgara/util/io/RecordFileImpl.java > /dev/null
ls util/java/org/mulgara/util/io/SetDataConverter.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/AVLComparator.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/AVLFile.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/AVLNode.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/AbstractBlockFile.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/Block.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/BlockFile.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/FreeList.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/IOBlockFile.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/LockFile.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/ManagedBlockFile.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/MappedBlockFile.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/PersistableMetaRoot.java > /dev/null
ls util-xa/java/org/mulgara/store/xa/XAUtils.java > /dev/null
